name:                SASL-Compiler
version:             0.1.0.0
github:              "githubuser/SASL-Compiler"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/SASL-Compiler#readme>

dependencies:
- graphviz
- containers
- mtl
- megaparsec
- base >= 4.7 && < 5
- text
- fgl
- optparse-applicative
- haskeline

benchmarks:
  countmin-bench:
    main: Main.hs
    source-dirs: bench
    dependencies:
      - criterion
      - SASL-Compiler

ghc-options: -Wall

library:
  source-dirs: src

executables:
  SASL-Compiler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - megaparsec
    - SASL-Compiler

tests:
  SASL-Compiler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - HUnit
    - SASL-Compiler